### ISSUE TITLE
Im using this on d3

### ISSUE THREAD

**Issue by Sageskully** [bennybroseph/AutoHotKey_Scripts#4]
i got it to work befor just updated it to v4.0 but when i use it it wont let me use it in gamer it switches to my desktop i re configured a few times and reinstalled it but idk why it is doing this i cant use autp pick up or any butten really but attack PS THIS THING IS AMAZING WHEN IT WORKS THANK YOU SO MUCH !!!!!!

**Comment by bennybroseph** [comment]
Is the game in borderless window mode? Otherwise, could you better describe the issue? When does it switch to your desktop?

**Comment by Sageskully** [comment]
It was not in windowed full screen that was the problem. I feel dumb I installed it on a new pc XD it was jumping to desktop when i tried to swap to free mouse or inventory mode for future i have used this for about a year now it is a AMAZING program and it seems to have a Amazing dev thank you for your quick reply :) this works on a shadow gamming rig account nicely
